/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Settings = {
  _id: string;
  _type: 'settings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  favicon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  socialTwitter?: string;
  socialLinkedin?: string;
  socialGithub?: string;
  socialInstagram?: string;
  socialFacebook?: string;
  socialYoutube?: string;
  copyright?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type LegalText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: 'span';
    _key: string;
  }>;
  style?: 'normal';
  listItem?: 'bullet';
  markDefs?: Array<{
    href?: string;
    openInNewTab?: boolean;
    _type: 'link';
    _key: string;
  }>;
  level?: number;
  _type: 'block';
  _key: string;
}>;

export type Legal = {
  _id: string;
  _type: 'legal';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle: string;
  seoDescription: string;
  lastUpdated: string;
  privacyPolicy: LegalText;
  termsAndConditions: LegalText;
  cookiePolicy: LegalText;
};

export type Homepage = {
  _id: string;
  _type: 'homepage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seoTitle: string;
  seoDescription: string;
};

export type ContactPage = {
  _id: string;
  _type: 'contactPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seoTitle: string;
  seoDescription: string;
};

export type BlogPage = {
  _id: string;
  _type: 'blogPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seoTitle: string;
  seoDescription: string;
};

export type Article = {
  _id: string;
  _type: 'article';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishedAt: string;
  excerpt: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h2' | 'h3' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          openInNewTab?: boolean;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: 'image';
        _key: string;
      }
  >;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  seoTitle: string;
  seoDescription: string;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | LegalText
  | Legal
  | Homepage
  | ContactPage
  | BlogPage
  | Article
  | Slug
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/schemas/documents/article/article.queries.ts
// Variable: ARTICLES_QUERY
// Query: *[_type == "article"] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    image { asset->{ _id, url, metadata { lqip } }, alt, crop, hotspot }  }
export type ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
      } | null;
    } | null;
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
}>;

// Source: src/sanity/schemas/documents/article/article.queries.ts
// Variable: ARTICLE_BY_SLUG_QUERY
// Query: *[_type == "article" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    excerpt,    content[] {      ...,      _type == "image" => {        ...,        asset->{ _id, url, metadata { lqip } }, alt, crop, hotspot      }    },    publishedAt,    image { asset->{ _id, url, metadata { lqip } }, alt, crop, hotspot },    seoTitle,    seoDescription  }
export type ARTICLE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h2' | 'h3' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          openInNewTab?: boolean;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string;
        _type: 'image';
        _key: string;
      }
  >;
  publishedAt: string;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
      } | null;
    } | null;
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  seoTitle: string;
  seoDescription: string;
} | null;

// Source: src/sanity/schemas/documents/article/article.queries.ts
// Variable: ARTICLE_SLUGS_QUERY
// Query: *[_type == "article" && defined(slug.current)] {    "slug": slug.current,    publishedAt,    _updatedAt  }
export type ARTICLE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
  publishedAt: string;
  _updatedAt: string;
}>;

// Source: src/sanity/schemas/documents/blog-page/blog-page.queries.ts
// Variable: BLOG_PAGE_QUERY
// Query: *[_type == "blogPage"][0]{  seoTitle,  seoDescription}
export type BLOG_PAGE_QUERY_RESULT = {
  seoTitle: string;
  seoDescription: string;
} | null;

// Source: src/sanity/schemas/documents/contact-page/contact-page.queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage"][0]{  seoTitle,  seoDescription}
export type CONTACT_PAGE_QUERY_RESULT = {
  seoTitle: string;
  seoDescription: string;
} | null;

// Source: src/sanity/schemas/documents/homepage/homepage.queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage"][0]{  seoTitle,  seoDescription}
export type HOMEPAGE_QUERY_RESULT = {
  seoTitle: string;
  seoDescription: string;
} | null;

// Source: src/sanity/schemas/documents/legal/legal.queries.ts
// Variable: LEGAL_QUERY
// Query: *[_type == "legal"][0]{  lastUpdated,  privacyPolicy,  termsAndConditions,  cookiePolicy,  seoTitle,  seoDescription}
export type LEGAL_QUERY_RESULT = {
  lastUpdated: string;
  privacyPolicy: LegalText;
  termsAndConditions: LegalText;
  cookiePolicy: LegalText;
  seoTitle: string;
  seoDescription: string;
} | null;

// Source: src/sanity/schemas/documents/settings/settings.queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "settings"][0]{  copyright,  "faviconUrl": favicon.asset->url,  "ogImageUrl": ogImage.asset->url,  socialTwitter,  socialLinkedin,  socialGithub,  socialInstagram,  socialFacebook,  socialYoutube}
export type SETTINGS_QUERY_RESULT = {
  copyright: string | null;
  faviconUrl: string | null;
  ogImageUrl: string | null;
  socialTwitter: string | null;
  socialLinkedin: string | null;
  socialGithub: string | null;
  socialInstagram: string | null;
  socialFacebook: string | null;
  socialYoutube: string | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "article"] | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    image { asset->{ _id, url, metadata { lqip } }, alt, crop, hotspot }\n  }\n': ARTICLES_QUERY_RESULT;
    '\n  *[_type == "article" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    content[] {\n      ...,\n      _type == "image" => {\n        ...,\n        asset->{ _id, url, metadata { lqip } }, alt, crop, hotspot\n      }\n    },\n    publishedAt,\n    image { asset->{ _id, url, metadata { lqip } }, alt, crop, hotspot },\n    seoTitle,\n    seoDescription\n  }\n': ARTICLE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "article" && defined(slug.current)] {\n    "slug": slug.current,\n    publishedAt,\n    _updatedAt\n  }\n': ARTICLE_SLUGS_QUERY_RESULT;
    '*[_type == "blogPage"][0]{\n  seoTitle,\n  seoDescription\n}': BLOG_PAGE_QUERY_RESULT;
    '*[_type == "contactPage"][0]{\n  seoTitle,\n  seoDescription\n}': CONTACT_PAGE_QUERY_RESULT;
    '*[_type == "homepage"][0]{\n  seoTitle,\n  seoDescription\n}': HOMEPAGE_QUERY_RESULT;
    '*[_type == "legal"][0]{\n  lastUpdated,\n  privacyPolicy,\n  termsAndConditions,\n  cookiePolicy,\n  seoTitle,\n  seoDescription\n}': LEGAL_QUERY_RESULT;
    '*[_type == "settings"][0]{\n  copyright,\n  "faviconUrl": favicon.asset->url,\n  "ogImageUrl": ogImage.asset->url,\n  socialTwitter,\n  socialLinkedin,\n  socialGithub,\n  socialInstagram,\n  socialFacebook,\n  socialYoutube\n}': SETTINGS_QUERY_RESULT;
  }
}
