#!/bin/sh
protected_branch='main'
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "$protected_branch" ]; then
    echo "================================================================"
    echo "ERROR: Direct commits to the 'main' branch are forbidden."
    echo "================================================================"
    echo "Please use the 'staging' branch for your development work"
    echo "or create a new feature branch from it."
    echo "----------------------------------------------------------------"
    exit 1
fi

pnpm ts && pnpm exec lint-staged